# Generated by Django 4.2.4 on 2023-10-09 15:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tokens',
            new_name='Token',
        ),
        migrations.RenameModel(
            old_name='TokenHistories',
            new_name='TokenHistory',
        ),
    ]
